[build-system]
requires = [
    "setuptools==79.0.1",
    "setuptools_scm[toml]==10.2.1",
    "wheel",
    "packaging",
    "psutil",
    "ninja==1.11.1",
    "pandas"
]
[tool.setuptools_scm]
write_to = "aiter/_version.py"
write_to_template = "__version__ = '{version}'\n"
fallback_version = "0.1.0"
